### ISSUE TITLE
Editing languages that have syntax

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#234]
While WeScheme may not, some languages have syntax that needs to be taken into account when inserting a node. For example, if you're editing a function call in Pyret:

    f(1, 3)

and insert `2` into the middle by editing the drop target between `1` and `3`, right now you'll get:

    f(1, 2 3)

The issue is that right now there's no mechanism for dealing with delimiters or other syntax when inserting (or for that matter, deleting) a node in the AST.

(Preston pointed this out today.)

**Comment by justinpombrio** [comment]
I _think_ this approach might work:
1. Insert a fake node into the parent's list of children, that when pretty-printed just outputs the text that was written.
2. Pretty-print the parent. The pretty-print function is where the knowledge of what delimiter to use (etc.) lives. So this should correctly pretty-print the parent and all of its children, including the new one you just added. (Note: when pretty-printing, should take indentation into account.)
3. The edit you just made is (i) delete the srcloc of the parent, (ii) insert the prettty-printed parent (that has the new child in it) into that srcloc.

**Comment by schanzer** [comment]
That sounds pretty solid to me, but remember that we compute the focus location based on the change event. With the above implementation (See item 3), inserting a new child will jump the focus to the *parent*. Perhaps we can be clever about diffing the parent strings, and generate an edit that *only* inserts the new syntax?

**Comment by prestontw** [comment]
Another case to be aware of: editing a function name inserts a space. For example, changing `f` in `fun f(x): x + 3 end` by expanding, double-clicking `f`, and replacing with `g` results in `fun g (x): x + 3 end`, which does not parse in Pyret.

**Comment by justinpombrio** [comment]
Idea: instead of generating the focus location by looking at the textual edit, we could generate the focus location by looking at the _difference in the ASTs_. I _think_ Oak's `ast-patch` algorithm already knows when a node was deleted or inserted, so it probably has enough information to implement `computeFocusNodeFromChanges` directly.

**Comment by schanzer** [comment]
That's a really interesting idea. My naive implementation would be to scan all the new nodes, find latest-occurring insertion, and focus on that. But a single group of `changes` could include multiple insertions, such that the most-recent insertion is actually _not_ the latest-occurring insertion.

There are also some small corner cases in which multiple children can have the same hash, so inserting another 5 in the middle of `(+ 1 5 5 5 5)` might wind up calling the _last_ 5 "new". This would be problematic.

**Comment by justinpombrio** [comment]
Oh, I didn't know that. What's an example of an edit you could make where the most-recent insertion was not the latest-occurring one?

**Comment by justinpombrio** [comment]
Two observations:

1. Looking at the old and new ASTs is insufficient to determine where to put focus. Emmanuel's example - `(+ 1 5 5 5)` becomes `(+ 1 5 5 5 5)`. Which 5 is new? All we have is the hashes, and all of `5`s have the same hash.

2. Looking at the _edit_ is also insufficient. For example, consider adding another argument to the JS function `x => x`, making it `(x, y) => x`. The edit is that `x` becomes `(x, y)`. This isn't terribly helpful for determining that the node `y` was added. (As humans we can, but no algorithm's going to be able to handle this generally enough.)

Thus we _have to_ use the srcloc of the drop target when determining the focus. Nothing else suffices.

**Comment by schanzer** [comment]
I'm not convinced that "nothing else suffices". In the second example, the `(x,y)` will be highlighted by the existing algorithm. That feels correct, if the node edited was `x` -- focus remains on the location of the edit. And using the droptarget location of `x` would give us the same result.

**Comment by justinpombrio** [comment]
Ah, let me be more clear about what I meant in the second example. I meant that there's a function block for the function `x => x`, with a drop target to the left and to the right of the argument `x`. You edit the drop target to the right of `x` and enter `y`. So `y` was inserted, and focus should be on `y`. The edit obscures this fact, though.

For the most-recent != last-occurring example: is there any way to _get_ that edit? I mean, is there any sequence of actions you can take in CMB that will produce that edit? I haven't been able to think of any myself.

**Comment by schanzer** [comment]
Ah, ok - I see what you mean. In that case, I think you're right.

As for my example: you can't generate that edit in CMB, but you can do it programmatically via the CM API. It's not a hard requirement that we do the right thing in this instance, but unless we have to give it up I so no reason not to try. :)

**Comment by prestontw** [comment]
Another case to be aware of:
```
fun f(x): x + 3 end
```
At one point, I had a drop target to the right of the end-parenthesis so one could add either a return annotation or denote the function as a block function. However, the current implementation of DT's would move what you typed _into the parentheses_, resulting in a parse error. For example, trying to add `-> Number` would result in `fun f(x -> Number): x + 3 end`. Something similar happens in reactors---we have a specific set of fields that we want students to be able to add.

Justin and I talked about optional pieces of syntax and how to show this in the UI. We should probably talk about this together at some point.

**Comment by justinpombrio** [comment]
# Roadmap

## Basic Functionality

First just check that these operations at least sometimes work

- [ ] delete node
- [ ] delete multiple nodes
- [ ] insert at droptarget
- [ ] insert at toplevel
- [ ] overwrite root nodes at toplevel by highlighting multiple nodes
- [ ] ctrl-enter edit a node
- [ ] copy
- [ ] paste
- [ ] cut
- [ ] drag&drop to drop target
- [ ] drag&drop to toplevel
- [ ] drag&drop to overwrite node 

## Testing

- [ ] Get the tests to pass again

## Fancy things

- [ ] Deleting an Optional should leave you with `?`
- [ ] Preston's case (see the previous comment). I don't even know what a good UI for that case _is_.

**Comment by justinpombrio** [comment]
Fixed by the [editing-syntax](https://github.com/bootstrapworld/codemirror-blocks/tree/editing-syntax) branch.
